from enum import StrEnum


class ItemStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    NEEDS_INFO = "NEEDS_INFO"


class ReasonCode(StrEnum):
    NOT_DELIVERED = "NOT_DELIVERED"
    WINDOW_EXPIRED = "WINDOW_EXPIRED"
    CATEGORY_NOT_RETURNABLE = "CATEGORY_NOT_RETURNABLE"
    CATEGORY_NOT_EXCHANGEABLE = "CATEGORY_NOT_EXCHANGEABLE"
    UNKNOWN_CATEGORY = "UNKNOWN_CATEGORY"
    QTY_EXCEEDED = "QTY_EXCEEDED"
    CONDITION_NOT_ACCEPTED = "CONDITION_NOT_ACCEPTED"
    DEFECT_CLAIM = "DEFECT_CLAIM"
    EXCHANGE_SCOPE = "EXCHANGE_SCOPE"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    PRICE_MISMATCH = "PRICE_MISMATCH"
    OVER_AUTO_LIMIT = "OVER_AUTO_LIMIT"


class DecisionCode(StrEnum):
    APPROVE = "APPROVE"
    DENY = "DENY"
    NEED_MANAGER = "NEED_MANAGER"
    NEED_INFO = "NEED_INFO"
