"""commerce schema

Revision ID: 087e60cb0ed6
Revises: base
Create Date: 2026-10-07 15:45:59.630984
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "087e60cb0ed6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("email", name=op.f("uq_customers_email")),
        schema="commerce",
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category_code", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
        schema="commerce",
    )
    op.create_table(
        "request_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.CheckConstraint("latency_ms >= 0", name=op.f("ck_request_log_latency_ms_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_log")),
        schema="commerce",
    )
    op.create_index(
        op.f("ix_commerce_request_log_ts"), "request_log", ["ts"], unique=False, schema="commerce"
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.String(length=255), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('placed', 'partially_shipped', 'shipped', 'delivered', 'cancelled')",
            name=op.f("ck_orders_status_valid"),
        ),
        sa.CheckConstraint("total_cents >= 0", name=op.f("ck_orders_total_cents_non_negative")),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["commerce.customers.id"], name=op.f("fk_orders_customer_id_customers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
        schema="commerce",
    )
    op.create_index(
        op.f("ix_commerce_orders_customer_id"),
        "orders",
        ["customer_id"],
        unique=False,
        schema="commerce",
    )
    op.create_table(
        "variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("size", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=255), nullable=False),
        sa.Column("list_price_cents", sa.Integer(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "list_price_cents >= 0", name=op.f("ck_variants_list_price_cents_non_negative")
        ),
        sa.CheckConstraint("stock >= 0", name=op.f("ck_variants_stock_non_negative")),
        sa.ForeignKeyConstraint(
            ["product_id"], ["commerce.products.id"], name=op.f("fk_variants_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variants")),
        schema="commerce",
    )
    op.create_index(
        op.f("ix_commerce_variants_product_id"),
        "variants",
        ["product_id"],
        unique=False,
        schema="commerce",
    )
    op.create_table(
        "returns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("refund_cents", sa.Integer(), nullable=True),
        sa.Column("reason_codes", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("policy_version", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(type = 'exchange') = (refund_cents IS NULL)", name=op.f("ck_returns_refund_by_type")
        ),
        sa.CheckConstraint(
            "status IN ('approved', 'pending_manager', 'received', 'inspection_passed', 'refunded', 'rejected')",
            name=op.f("ck_returns_status_valid"),
        ),
        sa.CheckConstraint("type IN ('return', 'exchange')", name=op.f("ck_returns_type_valid")),
        sa.CheckConstraint("refund_cents >= 0", name=op.f("ck_returns_refund_cents_non_negative")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["commerce.orders.id"], name=op.f("fk_returns_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_returns")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_returns_idempotency_key")),
        schema="commerce",
    )
    op.create_index(
        op.f("ix_commerce_returns_order_id"),
        "returns",
        ["order_id"],
        unique=False,
        schema="commerce",
    )
    op.create_table(
        "shipments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("carrier", sa.String(length=255), nullable=False),
        sa.Column("tracking_number", sa.String(length=255), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("eta", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'delivered' OR delivered_at IS NOT NULL",
            name=op.f("ck_shipments_delivered_has_time"),
        ),
        sa.CheckConstraint(
            "status IN ('label_created', 'in_transit', 'out_for_delivery', 'delivered', 'exception', 'lost')",
            name=op.f("ck_shipments_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["commerce.orders.id"], name=op.f("fk_shipments_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
        sa.UniqueConstraint("tracking_number", name=op.f("uq_shipments_tracking_number")),
        schema="commerce",
    )
    op.create_index(
        op.f("ix_commerce_shipments_order_id"),
        "shipments",
        ["order_id"],
        unique=False,
        schema="commerce",
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("shipment_id", sa.Uuid(), nullable=True),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.CheckConstraint("qty > 0", name=op.f("ck_order_items_qty_positive")),
        sa.CheckConstraint(
            "unit_price_cents >= 0", name=op.f("ck_order_items_unit_price_cents_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["commerce.orders.id"], name=op.f("fk_order_items_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["commerce.shipments.id"],
            name=op.f("fk_order_items_shipment_id_shipments"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["commerce.variants.id"],
            name=op.f("fk_order_items_variant_id_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        schema="commerce",
    )
    op.create_index(
        op.f("ix_commerce_order_items_order_id"),
        "order_items",
        ["order_id"],
        unique=False,
        schema="commerce",
    )
    op.create_index(
        op.f("ix_commerce_order_items_shipment_id"),
        "order_items",
        ["shipment_id"],
        unique=False,
        schema="commerce",
    )
    op.create_table(
        "refunds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("return_id", sa.Uuid(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'failed')", name=op.f("ck_refunds_status_valid")
        ),
        sa.CheckConstraint("amount_cents >= 0", name=op.f("ck_refunds_amount_cents_non_negative")),
        sa.ForeignKeyConstraint(
            ["return_id"], ["commerce.returns.id"], name=op.f("fk_refunds_return_id_returns")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_refunds_idempotency_key")),
        schema="commerce",
    )
    op.create_index(
        op.f("ix_commerce_refunds_return_id"),
        "refunds",
        ["return_id"],
        unique=False,
        schema="commerce",
    )
    op.create_table(
        "shipment_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status IN ('label_created', 'in_transit', 'out_for_delivery', 'delivered', 'exception', 'lost')",
            name=op.f("ck_shipment_events_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["commerce.shipments.id"],
            name=op.f("fk_shipment_events_shipment_id_shipments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_events")),
        schema="commerce",
    )
    op.create_index(
        op.f("ix_commerce_shipment_events_shipment_id"),
        "shipment_events",
        ["shipment_id"],
        unique=False,
        schema="commerce",
    )
    op.create_table(
        "return_items",
        sa.Column("return_id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("condition_claim", sa.Text(), nullable=True),
        sa.Column("exchange_variant_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "condition_claim IN ('new_with_tags', 'like_new', 'worn', 'defective')",
            name=op.f("ck_return_items_condition_valid"),
        ),
        sa.CheckConstraint("qty > 0", name=op.f("ck_return_items_qty_positive")),
        sa.ForeignKeyConstraint(
            ["exchange_variant_id"],
            ["commerce.variants.id"],
            name=op.f("fk_return_items_exchange_variant_id_variants"),
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["commerce.order_items.id"],
            name=op.f("fk_return_items_order_item_id_order_items"),
        ),
        sa.ForeignKeyConstraint(
            ["return_id"], ["commerce.returns.id"], name=op.f("fk_return_items_return_id_returns")
        ),
        sa.PrimaryKeyConstraint("return_id", "order_item_id", name=op.f("pk_return_items")),
        schema="commerce",
    )
    op.create_index(
        op.f("ix_commerce_return_items_order_item_id"),
        "return_items",
        ["order_item_id"],
        unique=False,
        schema="commerce",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_commerce_return_items_order_item_id"), table_name="return_items", schema="commerce"
    )
    op.drop_table("return_items", schema="commerce")
    op.drop_index(
        op.f("ix_commerce_shipment_events_shipment_id"),
        table_name="shipment_events",
        schema="commerce",
    )
    op.drop_table("shipment_events", schema="commerce")
    op.drop_index(op.f("ix_commerce_refunds_return_id"), table_name="refunds", schema="commerce")
    op.drop_table("refunds", schema="commerce")
    op.drop_index(
        op.f("ix_commerce_order_items_shipment_id"), table_name="order_items", schema="commerce"
    )
    op.drop_index(
        op.f("ix_commerce_order_items_order_id"), table_name="order_items", schema="commerce"
    )
    op.drop_table("order_items", schema="commerce")
    op.drop_index(op.f("ix_commerce_shipments_order_id"), table_name="shipments", schema="commerce")
    op.drop_table("shipments", schema="commerce")
    op.drop_index(op.f("ix_commerce_returns_order_id"), table_name="returns", schema="commerce")
    op.drop_table("returns", schema="commerce")
    op.drop_index(op.f("ix_commerce_variants_product_id"), table_name="variants", schema="commerce")
    op.drop_table("variants", schema="commerce")
    op.drop_index(op.f("ix_commerce_orders_customer_id"), table_name="orders", schema="commerce")
    op.drop_table("orders", schema="commerce")
    op.drop_index(op.f("ix_commerce_request_log_ts"), table_name="request_log", schema="commerce")
    op.drop_table("request_log", schema="commerce")
    op.drop_table("products", schema="commerce")
    op.drop_table("customers", schema="commerce")
    # ### end Alembic commands ###
